pipeline:
  check-diffs:
    image: bravissimolabs/alpine-git
    commands:
      - cd /drone/src/github.com/vespakoen/ontheweb/koenschmeets
      - git diff @~..@
  load-cache:
    image: plugins/sftp-cache:latest
    mount:
      - dwaler/node_modules
    restore: true
    when:
      event: [ pull_request, push ]
  build-dwaler:
    image: node:6
    commands:
      - cd dwaler
      - npm install
  publish-lektor:
    image: docker
    commands:
      - docker ps
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t vespakoen/lektor -f lektor/Dockerfile lektor
      - docker push vespakoen/lektor
    environment:
      - DOCKER_USERNAME=$$DOCKER_USERNAME
      - DOCKER_PASSWORD=$$DOCKER_PASSWORD
      - DOCKER_EMAIL=$$DOCKER_EMAIL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  build-koenschmeets:
    image: vespakoen/lektor:latest
    commands:
      - cd /drone/src/github.com/vespakoen/ontheweb/koenschmeets
      - lektor build -O public
  publish-koenschmeets:
    image: docker
    commands:
      - docker ps
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t vespakoen/koenschmeets -f koenschmeets/Dockerfile koenschmeets
      - docker push vespakoen/koenschmeets
    environment:
      - DOCKER_USERNAME=$$DOCKER_USERNAME
      - DOCKER_PASSWORD=$$DOCKER_PASSWORD
      - DOCKER_EMAIL=$$DOCKER_EMAIL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  save-cache:
    image: plugins/sftp-cache:latest
    mount:
      - dwaler/node_modules
    rebuild: true
    when:
      event: [ push ]
