pipeline:
  check-diffs:
    image: bravissimolabs/alpine-git
    commands:
      - cd /drone/src/github.com/vespakoen/ontheweb
      - git diff --name-only @~..@
      - git diff --exit-code --name-only @~..@ -- dwaler/ && echo "No changes in dwaler/" || echo "true" > dwaler_changed
      - git diff --exit-code --name-only @~..@ -- koenschmeets/ && echo "No changes in koenschmeets/" || echo "true" > koenschmeets_changed
      - git diff --exit-code --name-only @~..@ -- lektor/ && echo "No changes in lektor/" || echo "true" > lektor_changed
  load-cache:
    image: plugins/sftp-cache:latest
    mount:
      - dwaler/node_modules
    restore: true
    when:
      event: [ pull_request, push ]
  test-dwaler:
    image: node:6
    commands:
      - cat dwaler_changed || exit 0
      - cd dwaler
      - npm install
  publish-lektor:
    image: docker
    commands:
      - cat lektor_changed || exit 0
      - docker ps
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t vespakoen/lektor -f lektor/Dockerfile lektor
      - docker push vespakoen/lektor
    environment:
      - DOCKER_USERNAME=$$DOCKER_USERNAME
      - DOCKER_PASSWORD=$$DOCKER_PASSWORD
      - DOCKER_EMAIL=$$DOCKER_EMAIL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  build-koenschmeets:
    image: vespakoen/lektor:latest
    commands:
      - cat koenschmeets_changed || exit 0
      - cd /drone/src/github.com/vespakoen/ontheweb/koenschmeets
      - lektor build -O public
  publish-koenschmeets:
    image: docker
    commands:
      - cat koenschmeets_changed || exit 0
      - docker ps
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t vespakoen/koenschmeets -f koenschmeets/Dockerfile koenschmeets
      - docker push vespakoen/koenschmeets
    environment:
      - DOCKER_USERNAME=$$DOCKER_USERNAME
      - DOCKER_PASSWORD=$$DOCKER_PASSWORD
      - DOCKER_EMAIL=$$DOCKER_EMAIL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  save-cache:
    image: plugins/sftp-cache:latest
    mount:
      - dwaler/node_modules
    rebuild: true
    when:
      event: [ push ]
