pipeline:
  load-cache:
    image: plugins/sftp-cache:latest
    mount:
      - /drone/src/github.com/vespakoen/ontheweb/dwaler/node_modules
    restore: true
    when:
      event: [ pull_request, push ]
  build-dwaler:
    image: node:6
    commands:
      - cd dwaler
      - npm install
  build-koenschmeets:
    image: debian:wheezy
    commands:
      - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
      - apt-get update
      - apt-get install -y libssl-dev python2.7 python2.7-dev curl gcc libffi-dev imagemagick
      - cd /usr/local/bin && ln -s /usr/bin/python2.7 python
      - curl -sf https://www.getlektor.com/install.sh | sed '/stdin/d;s/input = .*/return/' > install.sh
      - chmod +x ./install.sh
      - ./install.sh
      - cd /drone/src/github.com/vespakoen/ontheweb/koenschmeets
      - lektor build -O public
  publish-koenschmeets:
    image: vespakoen/drone-docker:0.5.1
    debug: true
    repo: vespakoen/koenschmeets
    tag: ["latest", "${DRONE_BUILD_NUMBER}"]
    storage_driver: vfs
    context: koenschmeets
    dockerfile: koenschmeets/Dockerfile
  save-cache:
    image: plugins/sftp-cache:latest
    mount:
      - /drone/src/github.com/vespakoen/ontheweb/dwaler/node_modules
    rebuild: true
    when:
      event: [ push ]
services:
  cache:
    image: atmoz/sftp
    volumes:
      - /cache:/home/cache/cache
    command: cache:cache:1001
