pipeline:
  build-koenschmeets:
    image: ubuntu:16.04
    commands:
      - apt-get update && apt-get install libssl-dev python-dev curl imagemagick
      - curl -sf https://www.getlektor.com/install.sh | sh
      - lektor --help
