pipeline:
  build-koenschmeets:
    image: debian:jessie
    commands:
      - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
      - apt-get update && apt-get install -y libssl-dev python-dev curl imagemagick
      - curl -sf https://www.getlektor.com/install.sh | sh
      - lektor --help
