# SSL
https-portal:
  image: steveltn/https-portal
  restart: always
  ports:
    - 80:80
    - 443:443
  links:
    - koenschmeetswww
    - koenschmeetsci
    - dwalerwww
    - hummingwww
    - tileswww
  volumes:
    - /data/ssl_certs:/var/lib/https-portal
  environment:
    DOMAINS: >
      koenschmeets.nl -> http://koenschmeetswww,
      www.koenschmeets.nl -> http://koenschmeetswww,
      ci.koenschmeets.nl -> http://koenschmeetsci:8000,
      tiles.koenschmeets.nl -> http://tileswww:8080,
      www.dwaler.com -> http://dwalerwww,
      dwaler.com -> http://dwalerwww,
      tiles.dwaler.com -> http://tileswww:8080,
      www.humming.guru -> http://hummingwww,
      humming.guru -> http://hummingwww,
      tiles.humming.guru -> http://tileswww:8080
    STAGE: production
    WEBSOCKET: "true"

# KOENSCHMEETS
koenschmeetswww:
  image: vespakoen/koenschmeets:latest
  restart: always

# CI
koenschmeetsci:
  image: drone/drone:0.5
  restart: always
  privileged: true
  environment:
    DRONE_GITHUB: "true"
    DRONE_GITHUB_CLIENT: $DRONE_GITHUB_CLIENT
    DRONE_GITHUB_SECRET: $DRONE_GITHUB_SECRET
    DRONE_AGENT_SECRET: $DRONE_AGENT_SECRET
    DRONE_ADMIN: vespakoen
    I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: "true"
    I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: "true"
    DRONE_DEBUG: "true"
  volumes:
   - "/data/drone:/var/lib/drone"
   - "/var/run/docker.sock:/var/run/docker.sock"
  ports:
    - 8000:8000
koenschmeetsci-agent:
  image: drone/drone:0.5
  restart: always
  environment:
    DRONE_SERVER: http://koenschmeetsci:8000
    DRONE_SECRET: $DRONE_AGENT_SECRET
    DRONE_TOKEN: $DRONE_USER_TOKEN
    DRONE_PLUGIN_NETRC: "true"
    I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: "true"
    I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: "true"
    DRONE_DEBUG: "true"
    DRONE_TIMEOUT: "50h"
    # DRONE_PLUGIN_PULL: "false"
    DRONE_PLUGIN_PRIVILEGED: "plugins/docker,plugins/docker:*"
  links:
    - koenschmeetsci
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/root/.vagrant.d/insecure_private_key:/vagrant_key"
  command: agent
koenschmeetsci-cache:
  image: vespakoen/sftp-cache
  ports:
    - "2222:22"
  volumes:
    - /data/cache:/home/cache/share
  command: ${SFTP_CACHE_USERNAME}:${SFTP_CACHE_PASSWORD}:1001

# DWALER
dwalerwww:
  image: vespakoen/dwaler:latest
  environment:
    DWALER_PORT: 80
  restart: always

# HUMMINGGURU
hummingwww:
  image: tutum/hello-world
  restart: always

# VECTOR TILES
tileswww:
  image: vespakoen/tiles:latest
  restart: always
  environment:
    TILES_PATH: /planet.mbtiles
  volumes:
    - /data/tiles/planet.mbtiles:/planet.mbtiles

# BROUTER
# brouterwww:
#   image: vespakoen/brouter:latest
#   restart: always

# OVERPASS-API
# overpasswww:
#   image: vespakoen/overpass-api:latest
#   restart: always
#   command: bin/init_osm3s.sh planet.osm.bz2 "db/" "./" --meta