# SSL
https-portal:
  image: steveltn/https-portal
  ports:
    - 80:80
    - 443:443
  links:
    - koenschmeetswww
    - koenschmeetsci
    - dwalerwww
    - hummingwww
  environment:
    DOMAINS: >
      koenschmeets.nl -> http://koenschmeetswww,
      www.koenschmeets.nl -> http://koenschmeetswww,
      ci.koenschmeets.nl -> http://koenschmeetsci:8000,
      www.dwaler.com -> http://dwalerwww,
      dwaler.com -> http://dwalerwww,
      www.humming.guru -> http://hummingwww,
      humming.guru -> http://hummingwww
    PRODUCTION: "true"
    WEBSOCKET: "true"

# KOENSCHMEETS
koenschmeetswww:
  build: koenschmeets
koenschmeetsci:
  image: vespakoen/drone:0.5.1
  restart: always
  privileged: true
  environment:
    DRONE_GITHUB: "true"
    DRONE_GITHUB_CLIENT: $DRONE_GITHUB_CLIENT
    DRONE_GITHUB_SECRET: $DRONE_GITHUB_SECRET
    DRONE_AGENT_SECRET: $DRONE_AGENT_SECRET
    DRONE_ADMIN: vespakoen
    I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: "true"
    I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: "true"
    DRONE_DEBUG: "true"
  volumes:
   - "/drone:/var/lib/drone"
   - "/var/run/docker.sock:/var/run/docker.sock"
koenschmeetsci-agent:
  image: vespakoen/drone:0.5.1
  restart: always
  environment:
    DRONE_SERVER: http://koenschmeetsci:8000
    DRONE_SECRET: $DRONE_AGENT_SECRET
    DRONE_TOKEN: $DRONE_USER_TOKEN
    DRONE_PLUGIN_NETRC: "true"
    I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: "true"
    I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: "true"
    DRONE_DEBUG: "true"
    # DRONE_PLUGIN_PULL: "false"
    DRONE_PLUGIN_PRIVILEGED: "plugins/docker,plugins/docker:*,vespakoen/drone-docker:*"
  links:
    - koenschmeetsci
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: agent

# DWALER
dwalerwww:
  image: tutum/hello-world

# HUMMINGGURU
hummingwww:
  image: tutum/hello-world
