# SSL
https-portal:
  image: vespakoen/https-portal
  restart: always
  ports:
    - 80:80
    - 443:443
  links:
    - koenschmeetswww
    - koenschmeetsci
    - dwalerwww
    - hummingwww
    - signal-server
    - vespavibes
  volumes:
    - /data/ssl_certs:/var/lib/https-portal
  environment:
    DOMAINS: >
      koenschmeets.nl -> http://koenschmeetswww,
      www.koenschmeets.nl -> http://koenschmeetswww,
      ci.koenschmeets.nl -> http://koenschmeetsci:8000,
      signalhub.koenschmeets.nl -> http://signal-server:3001,
      dwaler.com -> http://dwalerwww,
      www.dwaler.com -> http://dwalerwww,
      humming.guru -> http://hummingwww:8080,
      www.humming.guru -> http://hummingwww:8080,
      vespavibes.com -> http://vespavibes:8080,
      www.vespavibes.com -> http://vespavibes:8080
    STAGE: production
    WEBSOCKET: "true"
    RESOLVER: 127.0.0.11 valid=60s

# KOENSCHMEETS
koenschmeetswww:
  image: vespakoen/koenschmeets:latest
  restart: always

# CI
koenschmeetsci:
  image: drone/drone:0.5
  restart: always
  privileged: true
  environment:
    DRONE_GITHUB: "true"
    DRONE_GITHUB_CLIENT: $DRONE_GITHUB_CLIENT
    DRONE_GITHUB_SECRET: $DRONE_GITHUB_SECRET
    DRONE_AGENT_SECRET: $DRONE_AGENT_SECRET
    DRONE_ADMIN: vespakoen
    I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: "true"
    I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: "true"
    DRONE_DEBUG: "true"
  volumes:
   - "/data/drone:/var/lib/drone"
   - "/var/run/docker.sock:/var/run/docker.sock"
koenschmeetsci-agent:
  image: drone/drone:0.5
  restart: always
  environment:
    DRONE_SERVER: ws://koenschmeetsci:8000/ws/broker
    DRONE_SECRET: $DRONE_AGENT_SECRET
    # DRONE_TOKEN: $DRONE_USER_TOKEN
    DRONE_PLUGIN_NETRC: "true"
    I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: "true"
    I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: "true"
    DRONE_DEBUG: "true"
    DRONE_TIMEOUT: "50h"
    # DRONE_PLUGIN_PULL: "false"
    DRONE_PLUGIN_PRIVILEGED: "plugins/docker,plugins/docker:*"
  links:
    - koenschmeetsci
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/root/.vagrant.d/insecure_private_key:/vagrant_key"
  command: agent
koenschmeetsci-cache:
  image: vespakoen/sftp-cache
  ports:
    - "2222:22"
  volumes:
    - /data/cache:/home/cache/share
  command: ${SFTP_CACHE_USERNAME}:${SFTP_CACHE_PASSWORD}:1001

# DWALER
dwalerwww:
  image: vespakoen/dwaler:latest
  restart: always
  environment:
    DWALER_PORT: 80

# HUMMINGGURU
hummingwww:
  image: vespakoen/hummingguru
  restart: always

# VECTOR TILES
# tileswww:
#   image: vespakoen/tiles:latest
#   restart: always
#   environment:
#     TILES_PATH: /data/planet.mbtiles
#   volumes:
#     - /data/tiles:/data

# # BROUTER PROXY
# brouterwww:
#   image: vespakoen/brouter-proxy:latest
#   restart: always
#   environment:
#     BROUTER_PROXY_PORT: 80

# # OVERPASS-API
# overpasswww:
#   image: vespakoen/overpass-api:latest
#   restart: always
#   environment:
#     EXEC_DIR: /srv/osm3s
#     DB_DIR: /srv/osm3s/db

signal-server:
  image: vespakoen/signal-server:latest

coturn:
  image: bprodoehl/turnserver
  restart: always
  net: host
  restart: on-failure:10
  ports:
    - "3478:3478"
    - "3478:3478/udp"

vespavibes:
  image: vespakoen/vespavibes
  restart: always